version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: proGRAMMER6996!@#
      POSTGRES_DB: scms
    networks:
      - mbr
networks:
  mbr: